/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as RelativeRouteImport } from './routes/relative'
import { Route as AdminActivitiesRouteImport } from './routes/admin/activities'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminFacilitiesRouteImport } from './routes/admin/facilities'
import { Route as AdminKioskPageRouteImport } from './routes/admin/kioskPage'
import { Route as AdminSensorEventsRouteImport } from './routes/admin/sensor-events'
import { Route as AdminSensorsRouteImport } from './routes/admin/sensors'
import { Route as AdminSigninRouteImport } from './routes/admin/signin'
import { Route as AdminVisitsRouteImport } from './routes/admin/visits'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthUnauthorizedRouteImport } from './routes/auth/unauthorized'
import { Route as CitizenIndexRouteImport } from './routes/citizen/index'
import { Route as CitizenActivitiesRouteImport } from './routes/citizen/activities'
import { Route as CitizenAppointmentsRouteImport } from './routes/citizen/appointments'
import { Route as CitizenRelativesRouteImport } from './routes/citizen/relatives'
import { Route as RelativeIndexRouteImport } from './routes/relative/index'
import { Route as RelativeCitizenIdRouteImport } from './routes/relative/$citizenId'
import { Route as ServicePartnerSigninRouteImport } from './routes/servicePartner/signin'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './routes/auth/accept-invitation.$invitationId'
import { Route as RelativeCitizenIdIndexRouteImport } from './routes/relative/$citizenId/index'
import { Route as RelativeCitizenIdActivitiesRouteImport } from './routes/relative/$citizenId/activities'
import { Route as RelativeCitizenIdCalendarRouteImport } from './routes/relative/$citizenId/calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const RelativeRoute = RelativeRouteImport.update({
  id: '/relative',
  path: '/relative',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKioskPageRoute = AdminKioskPageRouteImport.update({
  id: '/kioskPage',
  path: '/kioskPage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSensorEventsRoute = AdminSensorEventsRouteImport.update({
  id: '/sensor-events',
  path: '/sensor-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSensorsRoute = AdminSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSigninRoute = AdminSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenActivitiesRoute = CitizenActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenAppointmentsRoute = CitizenAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenRelativesRoute = CitizenRelativesRouteImport.update({
  id: '/relatives',
  path: '/relatives',
  getParentRoute: () => CitizenRoute,
} as any)
const RelativeIndexRoute = RelativeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RelativeRoute,
} as any)
const RelativeCitizenIdRoute = RelativeCitizenIdRouteImport.update({
  id: '/$citizenId',
  path: '/$citizenId',
  getParentRoute: () => RelativeRoute,
} as any)
const ServicePartnerSigninRoute = ServicePartnerSigninRouteImport.update({
  id: '/servicePartner/signin',
  path: '/servicePartner/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/auth/accept-invitation/$invitationId',
    path: '/auth/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RelativeCitizenIdIndexRoute = RelativeCitizenIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RelativeCitizenIdRoute,
} as any)
const RelativeCitizenIdActivitiesRoute =
  RelativeCitizenIdActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => RelativeCitizenIdRoute,
  } as any)
const RelativeCitizenIdCalendarRoute =
  RelativeCitizenIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => RelativeCitizenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/relative': typeof RelativeRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/kioskPage': typeof AdminKioskPageRoute
  '/admin/sensor-events': typeof AdminSensorEventsRoute
  '/admin/sensors': typeof AdminSensorsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/citizen/activities': typeof CitizenActivitiesRoute
  '/citizen/appointments': typeof CitizenAppointmentsRoute
  '/citizen/relatives': typeof CitizenRelativesRoute
  '/relative/$citizenId': typeof RelativeCitizenIdRouteWithChildren
  '/servicePartner/signin': typeof ServicePartnerSigninRoute
  '/citizen/': typeof CitizenIndexRoute
  '/relative/': typeof RelativeIndexRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/relative/$citizenId/activities': typeof RelativeCitizenIdActivitiesRoute
  '/relative/$citizenId/calendar': typeof RelativeCitizenIdCalendarRoute
  '/relative/$citizenId/': typeof RelativeCitizenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/kioskPage': typeof AdminKioskPageRoute
  '/admin/sensor-events': typeof AdminSensorEventsRoute
  '/admin/sensors': typeof AdminSensorsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/citizen/activities': typeof CitizenActivitiesRoute
  '/citizen/appointments': typeof CitizenAppointmentsRoute
  '/citizen/relatives': typeof CitizenRelativesRoute
  '/servicePartner/signin': typeof ServicePartnerSigninRoute
  '/citizen': typeof CitizenIndexRoute
  '/relative': typeof RelativeIndexRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/relative/$citizenId/activities': typeof RelativeCitizenIdActivitiesRoute
  '/relative/$citizenId/calendar': typeof RelativeCitizenIdCalendarRoute
  '/relative/$citizenId': typeof RelativeCitizenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/relative': typeof RelativeRouteWithChildren
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/kioskPage': typeof AdminKioskPageRoute
  '/admin/sensor-events': typeof AdminSensorEventsRoute
  '/admin/sensors': typeof AdminSensorsRoute
  '/admin/signin': typeof AdminSigninRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/unauthorized': typeof AuthUnauthorizedRoute
  '/citizen/activities': typeof CitizenActivitiesRoute
  '/citizen/appointments': typeof CitizenAppointmentsRoute
  '/citizen/relatives': typeof CitizenRelativesRoute
  '/relative/$citizenId': typeof RelativeCitizenIdRouteWithChildren
  '/servicePartner/signin': typeof ServicePartnerSigninRoute
  '/citizen/': typeof CitizenIndexRoute
  '/relative/': typeof RelativeIndexRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/relative/$citizenId/activities': typeof RelativeCitizenIdActivitiesRoute
  '/relative/$citizenId/calendar': typeof RelativeCitizenIdCalendarRoute
  '/relative/$citizenId/': typeof RelativeCitizenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/citizen'
    | '/relative'
    | '/admin/activities'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/kioskPage'
    | '/admin/sensor-events'
    | '/admin/sensors'
    | '/admin/signin'
    | '/admin/visits'
    | '/auth/profile'
    | '/auth/signin'
    | '/auth/unauthorized'
    | '/citizen/activities'
    | '/citizen/appointments'
    | '/citizen/relatives'
    | '/relative/$citizenId'
    | '/servicePartner/signin'
    | '/citizen/'
    | '/relative/'
    | '/auth/accept-invitation/$invitationId'
    | '/relative/$citizenId/activities'
    | '/relative/$citizenId/calendar'
    | '/relative/$citizenId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/activities'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/kioskPage'
    | '/admin/sensor-events'
    | '/admin/sensors'
    | '/admin/signin'
    | '/admin/visits'
    | '/auth/profile'
    | '/auth/signin'
    | '/auth/unauthorized'
    | '/citizen/activities'
    | '/citizen/appointments'
    | '/citizen/relatives'
    | '/servicePartner/signin'
    | '/citizen'
    | '/relative'
    | '/auth/accept-invitation/$invitationId'
    | '/relative/$citizenId/activities'
    | '/relative/$citizenId/calendar'
    | '/relative/$citizenId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/citizen'
    | '/relative'
    | '/admin/activities'
    | '/admin/dashboard'
    | '/admin/facilities'
    | '/admin/kioskPage'
    | '/admin/sensor-events'
    | '/admin/sensors'
    | '/admin/signin'
    | '/admin/visits'
    | '/auth/profile'
    | '/auth/signin'
    | '/auth/unauthorized'
    | '/citizen/activities'
    | '/citizen/appointments'
    | '/citizen/relatives'
    | '/relative/$citizenId'
    | '/servicePartner/signin'
    | '/citizen/'
    | '/relative/'
    | '/auth/accept-invitation/$invitationId'
    | '/relative/$citizenId/activities'
    | '/relative/$citizenId/calendar'
    | '/relative/$citizenId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CitizenRoute: typeof CitizenRouteWithChildren
  RelativeRoute: typeof RelativeRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  ServicePartnerSigninRoute: typeof ServicePartnerSigninRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relative': {
      id: '/relative'
      path: '/relative'
      fullPath: '/relative'
      preLoaderRoute: typeof RelativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kioskPage': {
      id: '/admin/kioskPage'
      path: '/kioskPage'
      fullPath: '/admin/kioskPage'
      preLoaderRoute: typeof AdminKioskPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sensor-events': {
      id: '/admin/sensor-events'
      path: '/sensor-events'
      fullPath: '/admin/sensor-events'
      preLoaderRoute: typeof AdminSensorEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sensors': {
      id: '/admin/sensors'
      path: '/sensors'
      fullPath: '/admin/sensors'
      preLoaderRoute: typeof AdminSensorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signin': {
      id: '/admin/signin'
      path: '/signin'
      fullPath: '/admin/signin'
      preLoaderRoute: typeof AdminSigninRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/unauthorized': {
      id: '/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/activities': {
      id: '/citizen/activities'
      path: '/activities'
      fullPath: '/citizen/activities'
      preLoaderRoute: typeof CitizenActivitiesRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/appointments': {
      id: '/citizen/appointments'
      path: '/appointments'
      fullPath: '/citizen/appointments'
      preLoaderRoute: typeof CitizenAppointmentsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/relatives': {
      id: '/citizen/relatives'
      path: '/relatives'
      fullPath: '/citizen/relatives'
      preLoaderRoute: typeof CitizenRelativesRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/relative/': {
      id: '/relative/'
      path: '/'
      fullPath: '/relative/'
      preLoaderRoute: typeof RelativeIndexRouteImport
      parentRoute: typeof RelativeRoute
    }
    '/relative/$citizenId': {
      id: '/relative/$citizenId'
      path: '/$citizenId'
      fullPath: '/relative/$citizenId'
      preLoaderRoute: typeof RelativeCitizenIdRouteImport
      parentRoute: typeof RelativeRoute
    }
    '/servicePartner/signin': {
      id: '/servicePartner/signin'
      path: '/servicePartner/signin'
      fullPath: '/servicePartner/signin'
      preLoaderRoute: typeof ServicePartnerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invitation/$invitationId': {
      id: '/auth/accept-invitation/$invitationId'
      path: '/auth/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relative/$citizenId/': {
      id: '/relative/$citizenId/'
      path: '/'
      fullPath: '/relative/$citizenId/'
      preLoaderRoute: typeof RelativeCitizenIdIndexRouteImport
      parentRoute: typeof RelativeCitizenIdRoute
    }
    '/relative/$citizenId/activities': {
      id: '/relative/$citizenId/activities'
      path: '/activities'
      fullPath: '/relative/$citizenId/activities'
      preLoaderRoute: typeof RelativeCitizenIdActivitiesRouteImport
      parentRoute: typeof RelativeCitizenIdRoute
    }
    '/relative/$citizenId/calendar': {
      id: '/relative/$citizenId/calendar'
      path: '/calendar'
      fullPath: '/relative/$citizenId/calendar'
      preLoaderRoute: typeof RelativeCitizenIdCalendarRouteImport
      parentRoute: typeof RelativeCitizenIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminKioskPageRoute: typeof AdminKioskPageRoute
  AdminSensorEventsRoute: typeof AdminSensorEventsRoute
  AdminSensorsRoute: typeof AdminSensorsRoute
  AdminSigninRoute: typeof AdminSigninRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminKioskPageRoute: AdminKioskPageRoute,
  AdminSensorEventsRoute: AdminSensorEventsRoute,
  AdminSensorsRoute: AdminSensorsRoute,
  AdminSigninRoute: AdminSigninRoute,
  AdminVisitsRoute: AdminVisitsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitizenRouteChildren {
  CitizenActivitiesRoute: typeof CitizenActivitiesRoute
  CitizenAppointmentsRoute: typeof CitizenAppointmentsRoute
  CitizenRelativesRoute: typeof CitizenRelativesRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenActivitiesRoute: CitizenActivitiesRoute,
  CitizenAppointmentsRoute: CitizenAppointmentsRoute,
  CitizenRelativesRoute: CitizenRelativesRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface RelativeCitizenIdRouteChildren {
  RelativeCitizenIdActivitiesRoute: typeof RelativeCitizenIdActivitiesRoute
  RelativeCitizenIdCalendarRoute: typeof RelativeCitizenIdCalendarRoute
  RelativeCitizenIdIndexRoute: typeof RelativeCitizenIdIndexRoute
}

const RelativeCitizenIdRouteChildren: RelativeCitizenIdRouteChildren = {
  RelativeCitizenIdActivitiesRoute: RelativeCitizenIdActivitiesRoute,
  RelativeCitizenIdCalendarRoute: RelativeCitizenIdCalendarRoute,
  RelativeCitizenIdIndexRoute: RelativeCitizenIdIndexRoute,
}

const RelativeCitizenIdRouteWithChildren =
  RelativeCitizenIdRoute._addFileChildren(RelativeCitizenIdRouteChildren)

interface RelativeRouteChildren {
  RelativeCitizenIdRoute: typeof RelativeCitizenIdRouteWithChildren
  RelativeIndexRoute: typeof RelativeIndexRoute
}

const RelativeRouteChildren: RelativeRouteChildren = {
  RelativeCitizenIdRoute: RelativeCitizenIdRouteWithChildren,
  RelativeIndexRoute: RelativeIndexRoute,
}

const RelativeRouteWithChildren = RelativeRoute._addFileChildren(
  RelativeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CitizenRoute: CitizenRouteWithChildren,
  RelativeRoute: RelativeRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  ServicePartnerSigninRoute: ServicePartnerSigninRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
